# Generated by Django 3.2.9 on 2021-11-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pins', to='pins.Tag'),
        ),
    ]
