# Generated by Django 3.2.9 on 2021-11-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_alter_pin_tags'),
        ('accounts', '0005_auto_20211127_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='savedPins',
            field=models.ManyToManyField(blank=True, null=True, related_name='savers', to='pins.Pin'),
        ),
    ]
