# Generated by Django 3.2.9 on 2021-11-29 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ManyToManyField(blank=True, default='', related_name='BoardCollaborator', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
                ('savedPins', models.ManyToManyField(blank=True, null=True, related_name='savers_boards', to='pins.Pin')),
            ],
            options={
                'ordering': ('-createdat',),
            },
        ),
    ]
